import { Icon } from "lucide-react"

const CarMakes=[
    {
        id:1,
        name:"Toyota",
    },
    {
        id:2,
        name:"Audi",
    },
    {
        id:3,
        name:"Mazda",
    },
    {
        id:4,
        name:"bmw",
    },
    {
        id:5,
        name:"Ferrari",
    },
    {
        id:6,
        name:"Ford",
    },
    {
        id:7,
        name:"Volkswagen",
    },
    {
        id:1,
        name:"Toyota",
    },
    {
        id:1,
        name:"Toyota",
    },
    {
        id:1,
        name:"Toyota",
    },
    {
        id:1,
        name:"Toyota",
    },
    {
        id:1,
        name:"Toyota",
    },
    {
        id:1,
        name:"Toyota",
    },
    {
        id:1,
        name:"Toyota",
    }
]


const Pricing=[
    {
        id:1,
        name:"$1000",
    },
    {
        id:2,
        name:"$5000",
    },
    {
        id:3,
        name:"$10000",
    },
    {
        id:4,
        name:"$20000",
    },
    {
        id:5,
        name:"$50000",
    },
    {
        id:6,
        name:"$100000",
    },
    {
        id:7,
        name:"$500000",
    }
]

const Category=[
    {
        id:1,
        name:"SUV",
        Icon:'https://cdn-icons-png.flaticon.com/128/13584/13584003.png'
    },
    {
        id:2,
        name:"Sedan",
        Icon:'https://cdn-icons-png.flaticon.com/128/3202/3202003.png'
    },
    {
        id:3,
        name:"Hatchback",
        icon:'https://cdn-icons-png.flaticon.com/128/5035/5035167.png'
    },
    {
        id:4,
        name:'Electric',
        icon:'https://cdn-icons-png.flaticon.com/128/4564/4564336.png'
    },
    {
        id:5,
        name:'Hybrid',
        icon:'https://cdn-icons-png.flaticon.com/128/3202/3202003.png'
    },
    {
        id:6,
        name:'Coupe',
        icon:'https://cdn-icons-png.flaticon.com/128/4391/4391630.png'
    },
]

export default{
    CarMakes,
    Pricing,
    Category
}